Replace url with uri | Second try
IntellectualSites/fastasyncvoxelsniper pull request #314
Opened 2023-10-01 12:02 UTC by TheMeinerLP

## Overview

Fixes #307

## Description

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

2023-10-01 16:41 UTC, Aurelien30000 requested changes
@NotMyFault Are you okay with "modern" ``var`` declaration introduced in this PR?
_As FAVS does not contain any of these, I think we should keep the code globally consistent and avoid ``var`` usage :shrug:_

2023-10-01 16:48 UTC, NotMyFault commented on src/main/java/com/thevoxelbox/voxelsniper/VoxelSniperPlugin.java
>              URLConnection conn = url.openConnection();
```suggestion
            URI uri = URI.create("https://api.curseforge.com/servermods/files?projectids=454430");
            URLConnection conn = uri.toURL().openConnection();
```

2023-10-01 16:49 UTC, NotMyFault commented
> @NotMyFault Are you okay with "modern" `var` declaration introduced in this PR? _As FAVS does not contain any of these, I think we should keep the code globally consistent and avoid `var` usage 🤷_

Likely unneeded, see my comment above.

2023-10-04 07:48 UTC, Aurelien30000 approved these changes

2023-10-04 08:26 UTC, NotMyFault approved these changes

2023-10-04 08:26 UTC, merged