Fix : Error 'org.bukkit.Art' but no parser exists
IntellectualSites/fastasyncvoxelsniper pull request #394
Opened 2024-11-25 10:46 UTC by Will33ELS

## Overview

Fixes the startup error in Paper 1.21.3.

Fixes [#{391}](https://github.com/IntellectualSites/fastasyncvoxelsniper/issues/391)

## Description
Using org.bukkit.Registry<Art> for managing painting templates instead of the deprecated org.bukkit.Art enumeration.
Bundles the Paper API version 1.21.3.

```[tasklist]
### Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [N/A] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).
```

2024-11-25 14:22 UTC, PierreSchwang commented
That's quite a jump removing a bunch of previously supported versions (e.g. 1.20.x) as well as removing Spigot support by depending on Paper specific API, no?

2024-11-25 22:28 UTC, PierreSchwang requested changes
Not sure if we really want to drop 1.20(.4) support already - dropping java 17 is alright for me.
Same goes for spigot compatibility.

2024-11-25 22:28 UTC, PierreSchwang commented on build.gradle.kts
> +    compileOnly("io.papermc.paper:paper-api:1.21.3-R0.1-SNAPSHOT")
versions are specified in the libs.versions.toml

2024-11-25 22:28 UTC, PierreSchwang commented on src/main/java/com/thevoxelbox/voxelsniper/command/executor/PaintExecutor.java
> +import net.kyori.adventure.key.Key;
no spigot compatibility

2024-11-25 22:28 UTC, PierreSchwang commented on src/main/java/com/thevoxelbox/voxelsniper/util/ArtHelper.java
> +import io.papermc.paper.registry.keys.PaintingVariantKeys;
same as above

2024-11-25 22:28 UTC, PierreSchwang commented on src/main/java/com/thevoxelbox/voxelsniper/brush/type/performer/PunishBrush.java
> +                entity.removePotionEffect(PotionEffectType.JUMP_BOOST);
+ other effects are breaking compatibility with 1.20 as well (https://helpch.at/docs/1.20.4/org/bukkit/potion/PotionEffectType.html)

2024-11-25 22:28 UTC, PierreSchwang commented on src/main/java/com/thevoxelbox/voxelsniper/command/executor/PaintExecutor.java
> +            final @Nullable @Argument("art") String art
That should have it's own argument / `VoxelCommandElement` ig - that was previously handled by the standardized Piston / WE EnumArgument

2024-11-27 13:22 UTC, Will33ELS commented
Hello @PierreSchwang,
For potion compatibility, I propose an enum that would contain both the old and new potion names. The server would use the potion name it recognizes by attempting to handle it via a try-catch block. What do you think?

2024-11-27 14:21 UTC, PierreSchwang requested changes
And please don't force push after review comments have been made - that makes reviewing unnecessarily difficult (as the PR is squashed either way)

2024-11-27 14:21 UTC, PierreSchwang commented on src/main/java/com/thevoxelbox/voxelsniper/command/executor/PaintExecutor.java
> +        ArtHelper.paint(player, Optional.ofNullable(art).map(a -> artRegistry.get(Key.key(a))).orElse(null));
Use NamespacedKey instead of kyori Key for spigot compatibility

2024-11-27 14:24 UTC, PierreSchwang commented
> Hello @PierreSchwang,
> 
> For potion compatibility, I propose an enum that would contain both the old and new potion names. The server would use the potion name it recognizes by attempting to handle it via a try-catch block. What do you think?

Easiest would be using the name constants with valueOf I guess - or if there is a better method without catching exceptions

2024-11-27 15:37 UTC, Will33ELS commented
Sorry for push force. 
I directly used the Registry for potion effects to avoid relying on variables that have changed. At the registry level, the names haven’t changed, so there shouldn’t be any issues with older versions.

2024-11-29 14:15 UTC, vjh0107 commented on src/main/java/com/thevoxelbox/voxelsniper/command/argument/ArtTypeArgument.java
> +public class ArtTypeArgument extends AbstractRegistryArgument<P> {
P ? ?

2024-11-29 14:16 UTC, vjh0107 commented on src/main/java/com/thevoxelbox/voxelsniper/command/argument/ArtTypeArgument.java
> +public class ArtTypeArgument extends AbstractRegistryArgument<P> {
P?

2024-12-04 13:53 UTC, Will33ELS commented
Hello @PierreSchwang, could you please review or accept this PR? Some people are already using my branch on their production servers.

2024-12-06 18:59 UTC, Aurelien30000 approved these changes

2024-12-06 19:48 UTC, PierreSchwang requested changes
Registry Access of EFFECT breaks compatibility with 1.20.2 (should be marked).
Please also update the supported versions in build.gradle.kts and the possible versions in the bug report template (.github folder)

2024-12-06 19:48 UTC, PierreSchwang commented on src/main/java/com/thevoxelbox/voxelsniper/brush/type/performer/PunishBrush.java
> +                entity.removePotionEffect(Registry.EFFECT.get(NamespacedKey.fromString("blindness")));
Use `NamespacedKey.minecraft("blindness"")` instead please - the IDE is completely covered with warnings otherwise, due to potential nullabilities

2024-12-06 19:48 UTC, PierreSchwang commented on src/main/java/com/thevoxelbox/voxelsniper/brush/type/performer/PunishBrush.java
> +                entity.removePotionEffect(Registry.EFFECT.get(NamespacedKey.fromString("blindness")));
I feel like potential nullability of `Registry#get` should be handled accordingly, and not ignored. Same goes for the `addEffect` calls down below as well.

2024-12-06 19:49 UTC, PierreSchwang commented
`/b paint` does not really seem to work for me with latest FAWE:
```
[20:47:33 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_21_3.PaperweightStarlightRelighterFactory as relighter factory.
[20:47:33 ERROR]: [ca.spottedleaf.moonrise.common.util.TickThread] Thread FAWE Fork Join Pool Secondary - 0 failed main thread check: Cannot move entity off-main
java.lang.Throwable: null
	at ca.spottedleaf.moonrise.common.util.TickThread.ensureTickThread(TickThread.java:52) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.server.ServerEntityLookup.checkThread(ServerEntityLookup.java:45) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup.moveEntity(EntityLookup.java:515) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at ca.spottedleaf.moonrise.patches.chunk_system.level.entity.EntityLookup$EntityCallback.onMove(EntityLookup.java:1046) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5048) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:5006) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.world.entity.decoration.HangingEntity.recalculateBoundingBox(HangingEntity.java:49) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.world.entity.decoration.Painting.onSyncedDataUpdated(Painting.java:58) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.network.syncher.SynchedEntityData.set(SynchedEntityData.java:70) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.network.syncher.SynchedEntityData.set(SynchedEntityData.java:62) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at net.minecraft.world.entity.decoration.Painting.setVariant(Painting.java:64) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.craftbukkit.entity.CraftPainting.setArt(CraftPainting.java:31) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at org.bukkit.craftbukkit.entity.CraftPainting.setArt(CraftPainting.java:24) ~[paper-1.21.3.jar:1.21.3-81-da71382]
	at fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar/com.thevoxelbox.voxelsniper.util.ArtHelper.paintAuto(ArtHelper.java:63) ~[fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar:?]
	at fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar/com.thevoxelbox.voxelsniper.brush.type.PaintingBrush.handleGunpowderAction(PaintingBrush.java:48) ~[fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar:?]
	at fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar/com.thevoxelbox.voxelsniper.brush.type.AbstractBrush.perform(AbstractBrush.java:77) ~[fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar:?]
	at fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar/com.thevoxelbox.voxelsniper.sniper.Sniper.snipeOnCurrentThread(Sniper.java:329) ~[fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar:?]
	at fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar/com.thevoxelbox.voxelsniper.sniper.Sniper.lambda$snipe$2(Sniper.java:189) ~[fastasyncvoxelsniper-3.2.2-SNAPSHOT-1733514243283.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```

2024-12-10 21:37 UTC, PierreSchwang approved these changes
should work ig

2024-12-14 10:03 UTC, Aurelien30000 approved these changes

2024-12-14 20:42 UTC, merged